export const people = [
  {
    emoji: "📈",
    firstname: "Thibaut",
    lastname: "Testeur de bureau",
    age: 34,
    job: "cto",
  },
  {
    emoji: "🤙",
    firstname: "Mat",
    lastname: "Thieu",
    age: 25,
    job: "dev",
  },
  {
    emoji: "📷",
    firstname: "Au",
    lastname: "Drey",
    age: 30,
    job: "dev",
  },
  {
    emoji: "🏓",
    firstname: "Fé",
    lastname: "Fé",
    age: 24,
    job: "produit",
  },
  {
    emoji: "🐈",
    firstname: "Émilien",
    lastname: "Les Chats",
    age: 33,
    job: "data",
  },
  {
    emoji: "🚴‍♂️",
    firstname: "Jo",
    lastname: "Jo",
    age: 24,
    job: "data",
  },
  {
    emoji: "🎸",
    firstname: "Kri",
    lastname: "Ko",
    age: 28,
    job: "infra",
  },
];
